version: '3'

services:
  casper-nctl:
    image: makesoftware/casper-nctl-staging:v158-v200-rc4
    container_name: casper-nctl-staging
    ports:
      - 11101-11105:11101-11105
      - 14101-14105:14101-14105
      - 18101-18105:18101-18105
      - 25101-25105:25101-25105
    environment:
      PREDEFINED_ACCOUNTS: 'true'
    volumes:
      - ./chainspec.toml.in:/home/casper/casper-node/resources/local/chainspec.toml.in
  nctlexplorer:
    image: makesoftware/casper-nctl-explorer:0.2.3-beta
    container_name: nctlexplorer-condor
    tty: true
    environment:
      Casper.Network.SDK.Web__NodeAddress: 'http://casper-nctl-staging:11101'
      Casper.Network.SDK.Web__SSEHost: 'casper-nctl-staging'
    ports:
      - 8080:80

  cors-anywhere:
    container_name: cors-anywhere
    profiles: ["cors-anywhere"]
    build:
      context: ./cors
      dockerfile: cors-anywhere.Dockerfile
    tty: true
    environment:
      PORT: 11100
    ports:
      - 11100:11100
